<!-- ----------------------------------------------------- -->

# Seasonality

### Weekly data

```{r}
dcmp <- bfs_web_deaths_weekly %>%
  tsibble::as_tsibble(index = Time) %>% 
  filter(Year < year) %>% 
  fabletools::model(feasts::STL(NumberOfDeaths ~ season(window = Inf)))

# fabletools::components(dcmp)
fabletools::components(dcmp) %>% 
  autoplot()
```

### Monthly data

```{r}
dcmp <- bfs_web_deaths_monthly %>%
  tsibble::as_tsibble(index = Time) %>% 
  filter(Year < year) %>% 
  fabletools::model(feasts::STL(deaths_month ~ season(window = Inf)))

# fabletools::components(dcmp)
fabletools::components(dcmp) %>% 
  autoplot()
```

<!-- ----------------------------------------------------- -->

# Outcome

### Weekly data

```{r echo=FALSE}
bfs_web_deaths_weekly %>% 
  filter(Year <= year_to) %>% 
  ggplot(aes(NumberOfDeaths)) +
  geom_histogram(binwidth = 10) +
  theme_minimal()
```

### Monthly data

```{r echo=FALSE}
bfs_web_deaths_monthly %>% 
  filter(Year <= year_to) %>% 
  ggplot(aes(deaths_month)) +
  geom_histogram(binwidth = 50) +
  theme_minimal()
```
