---
title: "Excess mortality: weekly data EDA"
author: "Radek Panczak"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
---


```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

options(scipen=999)
set.seed(12345)

library(pacman)
p_load(tidyverse, scales, kableExtra, tsibble, feasts, fable)

options(max.print = "75")
knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE)
knitr::opts_knit$set(width = 75)

mu <- Hmisc::markupSpecs$html
```

<!-- ----------------------------------------------------- -->

# Weekly number of deaths, 2010-2019

```{r include=FALSE}
weekly_2010_2019 <- read_rds("data/BfS/weekly_2010-2019.Rds") %>% 
  mutate(pandemic = 0)
weekly_2020_2021 <- read_rds("data/BfS/weekly_2020-2021.Rds") %>% 
  mutate(pandemic = 1)
weekly_2010_2021 <- weekly_2010_2019 %>% 
  bind_rows(weekly_2020_2021)

rm(weekly_2010_2019, weekly_2020_2021)
```

Last sixish years

```{r echo=FALSE}
weekly_2010_2021 %>% 
  filter(Year >= 2015) %>%
  filter(Ending < Sys.Date()) %>% 
  ggplot(aes(x = Ending)) +
  geom_ribbon(aes(ymin = lowerB, ymax = upperB, fill = Age), alpha = 0.1) +
  geom_line(aes(y = Expected, group = Age), colour = "gray60") + 
  geom_line(aes(y = NumberOfDeaths, colour = Age)) + 
  # geom_vline(aes(xintercept = as.Date("2020-02-24"))) +
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  ylab("") + xlab("Number of deaths")
```

# Seasonal plots

Only 65+ deaths!

```{r}
weekly <- weekly_2010_2021 %>% 
  filter(Age == "65+",
         !is.na(NumberOfDeaths)) %>% 
  as_tsibble(index = Ending)
```

```{r}
weekly %>% gg_season(NumberOfDeaths)
weekly %>% gg_season(NumberOfDeaths, polar = TRUE)
```

# ACF

```{r}
weekly %>% ACF(NumberOfDeaths) %>% autoplot()
```

# Decomp 

Pre COVID-19!

```{r}
dcmp <- weekly %>%
  filter(Ending <= as.Date("2019-12-31")) %>% 
  model(STL(NumberOfDeaths ~ season(window = Inf)))

# components(dcmp)

components(dcmp) %>% 
  autoplot()
```


<!-- ----------------------------------------------------- -->

# Computing Environment

`r mu$session()`