---
title: "Excess mortality: HMD & country data"
subtitle: "Changing age profile across pandemics"
author: "Radek Panczak"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
---

<!-- ----------------------------------------------------- -->

```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

options(scipen = 999)
set.seed(12345)
options(max.print = "75")

library(pacman)
p_load(tidyverse, readxl, janitor, lubridate, scales, magrittr, slider)

options(max.print = "75")
knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE,
                      # fig.width=8, fig.height=6,
                      # out.width="800px", out.height="600px",
                      dpi=300)
knitr::opts_knit$set(width = 75)

mu <- Hmisc::markupSpecs$html
```

<!-- ----------------------------------------------------- -->

# Mortality 

## HMD for three countries

[The Human Mortality Database](https://www.mortality.org/) `1x1` data.  

**Covering period to 2018 only!**  

Grouping age to 5-year age bands.  

<!-- Grouping age to: `<1, 1-4, 5-19, 20-39, 40-59, 60-79, >=80`.   -->

```{r}
read_hmd <- function(dataset) {
  read_rds(dataset) %>% 
    select(-Female, -Male) %>% 
    mutate(Age = ifelse(Age == "110+", "111", Age),
           Age = as.numeric(Age), 
           # Age_group = cut(Age, 
           # breaks = c(0, 1, 5, 20, 40, 60, 80, 112),
           # # labels = c("<1", "1-4", "5-19", "20-39", "40-59", "60-79","80+"), 
           # right=FALSE), 
           Age_group = cut(Age, 
                           breaks = c(seq(0, 90, 5), 113), 
                           # labels = c("0-9","10-19","20-29","30-39","40-49","50-59","60-69","70-79","80+")), 
                           right=FALSE)
    ) %>%
    group_by(Year, Age_group) %>% 
    summarise(Deaths = sum(Total)) %>% 
    ungroup() %>% 
    as_tibble()
}

hmd_ch_deaths <- read_hmd("data-raw/mortality_org/hmd_ch_deaths_raw.Rds") %>% 
  mutate(Country = "Switzerland") %>% relocate(Country)
# sjmisc::frq(hmd_ch_deaths, Age_group)

hmd_se_deaths <- read_hmd("data-raw/mortality_org/hmd_se_deaths_raw.Rds") %>% 
  mutate(Country = "Sweden") %>% relocate(Country)
# sjmisc::frq(hmd_se_deaths, Age_group)

hmd_es_deaths <- read_hmd("data-raw/mortality_org/hmd_es_deaths_raw.Rds") %>% 
  mutate(Country = "Spain") %>% relocate(Country)
# sjmisc::frq(hmd_es_deaths, Age_group)
```

## 2019-2020

### CH

Yearly totals data delivered by BfS.  

```{r}
ch_deaths <- read_csv("data-raw/BfS/Lieferung_Staub_2021.csv", 
                      col_types = cols(KalJahr = col_integer(),
                                       Alter = col_integer(),
                                       COUNT = col_integer()), 
                      trim_ws = TRUE) %>% 
  rename(Year = KalJahr) %>% 
  mutate(Age_group = cut(Alter, 
                         breaks = c(seq(0, 90, 5), 113), 
                         # labels = c("0-9","10-19","20-29","30-39","40-49","50-59","60-69","70-79","80+")), 
                         right=FALSE)
  ) %>% 
  group_by(Year, Age_group) %>% 
  summarise(Deaths = sum(COUNT)) %>% 
  ungroup() %>% 
  select(Year, Age_group, Deaths) %>% 
  mutate(Country = "Switzerland") %>% relocate(Country)
```

### SWE

Yearly totals data from SCB.  

```{r}
se_deaths <- read_xlsx("data-raw/SCB/BE0101D9_20210429-200440.xlsx", 
                       col_types = c("text", "text", "text", "numeric", "numeric"), 
                       skip = 2) %>% 
  remove_empty() %>% 
  clean_names() %>% 
  filter(!is.na(x2019)) %>% 
  select(-x1, -x3) %>% 
  mutate(Age = word(x2, 1),
         Age = str_replace(Age, fixed("100+"), "100"),
         Age = as.numeric(Age)) %>% 
  fill(Age) %>% 
  group_by(Age) %>% 
  summarize(x2019 = sum(x2019),
            x2020 = sum(x2020)) %>% 
  ungroup() %>% 
  pivot_longer(-Age, names_to = "Year", values_to = "Deaths") %>% 
  mutate(Year = as.numeric(str_replace(Year, fixed("x"), "")),
         Age_group = cut(Age, 
                         breaks = c(seq(0, 90, 5), 113), 
                         # labels = c("0-9","10-19","20-29","30-39","40-49","50-59","60-69","70-79","80+")), 
                         right=FALSE)
  ) %>% 
  group_by(Year, Age_group) %>% 
  summarise(Deaths = sum(Deaths)) %>% 
  ungroup() %>% 
  select(Year, Age_group, Deaths) %>% 
  mutate(Country = "Sweden") %>% relocate(Country)
```

### ESP

Yearly totals data from INE  

```{r}
es_deaths_2019 <- read_delim("data-raw/INE/Spain2019age.csv",
                             delim = ";",
                             locale = locale(grouping_mark = "."),
                             trim_ws = TRUE) %>% 
  mutate(Year = as.integer(Periodo)) %>% 
  mutate(Age = word(Edad, 1),
         Age = str_replace(Age, fixed("Menores"), "0"),
         Age = as.numeric(Age)
  ) %>% 
  mutate(Age_group = cut(Age, 
                         breaks = c(seq(0, 90, 5), 113), 
                         # labels = c("0-9","10-19","20-29","30-39","40-49","50-59","60-69","70-79","80+")), 
                         right=FALSE)
  ) %>% 
  group_by(Year, Age_group) %>% 
  summarise(Deaths = sum(Total)) %>% 
  ungroup() %>% 
  select(Year, Age_group, Deaths) %>% 
  mutate(Country = "Spain") %>% relocate(Country)

es_deaths_2020 <- read_delim("data-raw/INE/Spain2020weeklyage.csv",
                             delim = ";",
                             locale = locale(grouping_mark = "."),
                             trim_ws = TRUE) %>% 
  rename(Edad = `Edad (grupos quinquenales)`) %>% 
  filter(Edad != "Todas las edades") %>% 
  filter(Edad != "No consta") %>% 
  mutate(Year = as.integer(2020)) %>% 
  mutate(Age = str_replace(Edad, fixed("De "), ""),
         Age = word(Age, 1),
         Age = as.numeric(Age)
  ) %>% 
  mutate(Age_group = cut(Age, 
                         breaks = c(seq(0, 90, 5), 113), 
                         # labels = c("0-9","10-19","20-29","30-39","40-49","50-59","60-69","70-79","80+")), 
                         right=FALSE)
  ) %>% 
  group_by(Year, Age_group) %>% 
  summarise(Deaths = sum(Total)) %>% 
  ungroup() %>% 
  select(Year, Age_group, Deaths) %>% 
  mutate(Country = "Spain") %>% relocate(Country)

es_deaths <- bind_rows(es_deaths_2019, es_deaths_2020)
rm(es_deaths_2019, es_deaths_2020)
```

## Pandemics 

```{r}
analysis_years <- c(1890, 1918, 1957, 2020)

previous_years <- c(seq(1890 - 10, 1890 - 1),
                    seq(1918 - 10, 1918 - 1),
                    seq(1957 - 10, 1957 - 1),
                    seq(2020 - 10, 2020 - 1))
```

```{r echo=FALSE}
data <- bind_rows( 
  # HMD historical data
  hmd_ch_deaths %>% filter(Year %in% previous_years) %>% mutate(Type = "Previous"),
  hmd_ch_deaths %>% filter(Year %in% analysis_years) %>% mutate(Type = "Pandemic"), 
  
  hmd_es_deaths %>% filter(Year %in% previous_years) %>% mutate(Type = "Previous"),
  hmd_es_deaths %>% filter(Year %in% analysis_years) %>% mutate(Type = "Pandemic"), 
  
  hmd_se_deaths %>% filter(Year %in% previous_years) %>% mutate(Type = "Previous"),
  hmd_se_deaths %>% filter(Year %in% analysis_years) %>% mutate(Type = "Pandemic"), 
  
  # last two years
  ch_deaths %>% filter(Year %in% analysis_years) %>% mutate(Type = "Pandemic"),
  es_deaths %>% filter(Year %in% analysis_years) %>% mutate(Type = "Pandemic"),
  se_deaths %>% filter(Year %in% analysis_years) %>% mutate(Type = "Pandemic"),
  ch_deaths %>% filter(Year %in% previous_years) %>% mutate(Type = "Previous"),
  es_deaths %>% filter(Year %in% previous_years) %>% mutate(Type = "Previous"),
  se_deaths %>% filter(Year %in% previous_years) %>% mutate(Type = "Previous")
) %>%  
  arrange(Country, Year, Age_group) %>% 
  mutate(Pandemic = ifelse(Year %in% analysis_years, Year, NA)) %>% 
  fill(Pandemic, .direction = "up")

rm(hmd_ch_deaths, hmd_es_deaths, hmd_se_deaths,
   ch_deaths, es_deaths, se_deaths)
```

## Pops

```{r}
pop <- bind_rows(
  
  read_rds("data-raw/mortality_org/hmd_ch_pop_raw.Rds") %>% 
    mutate(Age = ifelse(Age == "110+", 110, Age),
           Age = as.numeric(Age)) %>% 
    mutate(Age_group = cut(Age, 
                           breaks = c(seq(0, 90, 5), 113), 
                           right=FALSE)
    ) %>% 
    group_by(Year, Age_group) %>% 
    summarise(Population = sum(Total)) %>% 
    ungroup() %>% 
    select(Year, Age_group, Population) %>% 
    mutate(Country = "Switzerland") %>% relocate(Country), 
  
  read_rds("data-raw/mortality_org/hmd_es_pop_raw.Rds") %>% 
    mutate(Age = ifelse(Age == "110+", 110, Age),
           Age = as.numeric(Age)) %>% 
    mutate(Age_group = cut(Age, 
                           breaks = c(seq(0, 90, 5), 113), 
                           right=FALSE)
    ) %>% 
    group_by(Year, Age_group) %>% 
    summarise(Population = sum(Total)) %>% 
    ungroup() %>% 
    select(Year, Age_group, Population) %>% 
    mutate(Country = "Spain") %>% relocate(Country),
  
  read_rds("data-raw/mortality_org/hmd_se_pop_raw.Rds") %>% 
    mutate(Age = ifelse(Age == "110+", 110, Age),
           Age = as.numeric(Age)) %>% 
    mutate(Age_group = cut(Age, 
                           breaks = c(seq(0, 90, 5), 113), 
                           right=FALSE)
    ) %>% 
    group_by(Year, Age_group) %>% 
    summarise(Population = sum(Total)) %>% 
    ungroup() %>% 
    select(Year, Age_group, Population) %>% 
    mutate(Country = "Sweden") %>% relocate(Country)
  
) %>% 
  group_by(Country) %>% 
  mutate(pop_min = min(Population),
         pop_max = max(Population),
         pop_scaled = (Population - pop_min) / (pop_max - pop_min)) %>% 
  ungroup() %>% 
  select(-pop_min, -pop_max) %>% 
  mutate(Year = ifelse(Year == 2019, 2020, Year)) %>% 
  filter(Year %in% analysis_years) %>% 
  rename(Pandemic = Year)

data %<>% left_join(pop)
```

<!-- ----------------------------------------------------- -->

# Viz

```{r echo=FALSE}
ggplot(data = data %>% filter(Type == "Previous"),
       aes(x = Age_group, y = Deaths)) + 
  # geom_boxplot(aes(colour = Age_group, weight = pop_scaled), varwidth = TRUE) +
  geom_boxplot(aes(colour = Age_group)) +
  geom_line(data = data %>% filter(Type == "Pandemic"), aes(group = Year)) +
  facet_grid(rows = vars(Country), cols = vars(Pandemic), scales = "free_y") + 
  scale_y_continuous(labels = label_number(accuracy = 0.1, suffix = "K", scale = 1e-4)) +
  scale_color_viridis_d() +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90)) +
  xlab("Age group") + labs(colour = "Age")

ggsave("paper/age_groups.png", dpi = 300, width = 297, height = 210, units = "mm")
```

```{r echo=FALSE}
ggplot(data = data %>% filter(Type == "Previous"),
       aes(x = Age_group, y = Deaths)) + 
  geom_line(aes(colour = Age_group, group = Year)) +
  geom_point(data = data %>% filter(Type == "Pandemic"), aes(group = Year)) +
  facet_grid(rows = vars(Country), cols = vars(Pandemic), scales = "free_y") + 
  scale_y_continuous(labels = label_number(accuracy = 0.1, suffix = "K", scale = 1e-4)) +
  scale_color_viridis_d() +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90)) +
  xlab("Age group")
```

```{r echo=FALSE}
ggplot(data = data %>% filter(Type == "Previous"),
       aes(x = Age_group, y = Deaths)) + 
  geom_jitter(aes(colour = Age_group, group = Year)) +
  geom_line(data = data %>% filter(Type == "Pandemic"), aes(group = Year)) +
  facet_grid(rows = vars(Country), cols = vars(Pandemic), scales = "free_y") + 
  scale_y_continuous(labels = label_number(accuracy = 0.1, suffix = "K", scale = 1e-4)) +
  scale_color_viridis_d() +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90)) +
  xlab("Age group")
```

<!-- ----------------------------------------------------- -->

# Computing Environment

`r mu$session()`


