---
title: "Excess mortality"
subtitle: "Comparison of monthly and weekly data use"
author: "Radek Panczak"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
  code_folding: show
self_contained: true
highlight: pygments
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---

<!-- ----------------------------------------------------- -->

```{r setup, include = FALSE}
set.seed(12345)
options(scipen = 999)
options(max.print = "75")

library(pacman)
p_load(tidyverse, magrittr, scales, 
       cmdstanr, posterior)
```

```{r knit-setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE)
knitr::opts_knit$set(width = 75)

mu <- Hmisc::markupSpecs$html
```

<!-- ----------------------------------------------------- -->

# Data & set up

## Misc

```{r}
## Counrtry 
COUNTRIES = c("Switzerland","Spain","Sweden")

## Pandemics & subsequent post-pandemic years to exclude
pandemic <- 2020

## Funcs
source("R/fn_global_serfling_nb_week_cmdstan.R")

## Starting year
START <- 2005
```

## Monthly data 

```{r}
## Population denominator
pops <- read_rds("data/deaths_monthly.Rds") %>% 
  filter(Month == 1) %>% 
  select(Year, Country, Population_obs) 

stmf_month <- read_rds("data/mortality_org/stmf_month.Rds") %>% 
  left_join(pops) %>% 
  mutate(si_one = sin(2*pi*Month/12),
         si_two = sin(4*pi*Month/12),
         co_one = cos(2*pi*Month/12),
         co_two = cos(4*pi*Month/12)) 
```

## Weekly data

Recalculating sin & cos data:  

```{r}
stmf_week <- read_rds("data/mortality_org/stmf_week.Rds") %>% 
  left_join(pops) %>% 
  mutate(
    si_one = sin(2*pi*Week/(365.25/7)),
    si_two = sin(4*pi*Week/((365.25/2)/7)),
    co_one = cos(2*pi*Week/(365.25/7)),
    co_two = cos(4*pi*Week/((365.25/2)/7))
  )

rm(pops)
```

Getting half of the year in 2021 - data kept until **Week 26**. That means it's *not strictly speaking half a year* since week 26 runs four days into July.  

```{r}
stmf_week %<>% 
  filter(! (Year == 2021 & Week > 26))
```

Problem of 53! Some years have one more week. Will be resolved later.  

```{r}
stmf_week %>% 
  filter(Week == 53) %>% 
  group_by(Year) %>% 
  summarise(Year = first(Year))
```

# Monthly results 

```{r}
monthly_results_month <- tibble()
monthly_results_year <- tibble()

for(COUNTRY in COUNTRIES) {
  
  ## Data 
  deaths_monthly <- stmf_month %>% 
    filter(Country == COUNTRY)
  
  ## Loop
  for (YEAR in (START+5):2021) {
    
    print(paste("Country:", COUNTRY, "Year:", YEAR, "Monthly loop."))
    
    m_glo <- fn_global_serfling_nb_cmdstan(YEAR, 
                                           deaths_monthly, 
                                           pandemic_years = pandemic, 
                                           pop = "obs",
                                           version = "last_5")
    
    
    monthly_results_month <- m_glo$pred_total_deaths %>% 
      dplyr::select(-starts_with("excess_year")) %>% 
      dplyr::mutate(Model = "Monthly") %>% 
      bind_rows(., monthly_results_month)
    
    monthly_results_year <- m_glo$pred_total_deaths %>% 
      filter(row_number() == 1) %>% 
      select(Country, Year, starts_with("excess_year")) %>% 
      dplyr::mutate(Model = "Monthly") %>% 
      bind_rows(., monthly_results_year)
    
    rm(m_glo)
    gc()
  }
}
```

# Weekly results 

Models estimated using **52 weeks only**!  

```{r}
weekly_results_month <- tibble()
weekly_results_year <- tibble()

for(COUNTRY in COUNTRIES) {
  
  ## Data 
  deaths_weekly <- stmf_week %>% 
    filter(Country == COUNTRY) %>% 
    filter(Week < 53)
  
  ## Loop
  for (YEAR in (START+5):2021) {
    
    print(paste("Country:", COUNTRY, "Year:", YEAR, "Monthly loop."))
    
    m_glo <- fn_global_serfling_nb_week_cmdstan(YEAR, 
                                                deaths_weekly, 
                                                pandemic_years = pandemic, 
                                                pop = "obs")
    
    
    weekly_results_month <- m_glo$pred_total_deaths %>% 
      dplyr::select(-starts_with("excess_year")) %>% 
      dplyr::mutate(Model = "Weekly") %>% 
      bind_rows(., weekly_results_month)
    
    weekly_results_year <- m_glo$pred_total_deaths %>% 
      filter(row_number() == 1) %>% 
      select(Country, Year, starts_with("excess_year")) %>% 
      dplyr::mutate(Model = "Weekly") %>% 
      bind_rows(., weekly_results_year)
    
    rm(m_glo)
    gc()
  }
}
```

```{r include=FALSE}
rm(deaths_monthly, deaths_weekly, COUNTRIES, pandemic, START); gc()
```


